"""add_multi_position_fields

Revision ID: 20241220_0003
Revises: 20241005_0002
Create Date: 2024-12-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20241220_0003'
down_revision = '20241005_0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_history', sa.Column('positions_data', sa.Text(), nullable=True))
    op.add_column('generation_history', sa.Column('total_general_price', sa.Float(), nullable=True))
    op.add_column('generation_history', sa.Column('positions_count', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_history', 'positions_count')
    op.drop_column('generation_history', 'total_general_price')
    op.drop_column('generation_history', 'positions_data')
    # ### end Alembic commands ###
